# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: admin
# skip-verify: true
insecure: true
port: 57400
timeout: 10s
encoding: json_ietf

targets:
  r1:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_anysec_peer
      - sros_anysec_peer_config
      - sros_anysec_sec_termination_policy
      - sros_epipe_instance_oper_state
      - sros_vprn_instance_oper_state
  r2:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_anysec_peer
      - sros_anysec_peer_config
      - sros_anysec_sec_termination_policy
      - sros_epipe_instance_oper_state
      - sros_vprn_instance_oper_state      
  r3:57400:
      subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
  r4:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats


subscriptions:

  sros_port_oper_state:
    paths:
      - /state/port[port-id=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 1s

  sros_port_stats:
    paths:
      - /state/port[port-id=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 1s

  sros_port_traffic_rate:
    paths:
      - /state/port[port-id=*]/ethernet/oper-speed
    mode: stream
    stream-mode: sample
    sample-interval: 1s

  sros_if_stats:
    paths:
      - /state/router[router-name=Base]/interface[interface-name=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 1s


  sros_anysec_peer:
    paths:
      - /state/anysec/tunnel-encryption/encryption-group[group-name=*]/peer[peer-ip-address=*]
    mode: stream
    stream-mode: sample
    sample-interval: 1s 
  
  sros_anysec_peer_config:
    paths:
      - /configure/anysec/tunnel-encryption/encryption-group[group-name=*]/peer[peer-ip-address=*]
    mode: stream
    stream-mode: target-defined
    sample-interval: 1s 

  sros_anysec_sec_termination_policy:
    paths:
      - /state/anysec/tunnel-encryption/security-termination-policy[policy-name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 1s 

  sros_epipe_instance_oper_state:
    paths:
      - /state/service/epipe[service-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 1s

  sros_vprn_instance_oper_state:
    paths:
      - /state/service/vprn[service-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 1s


outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
        - admin-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
        - replace:
            apply-on: "value"
            old: "enable"
            new: "1"
        - replace:
            apply-on: "value"
            old: "disable"
            new: "0"
